<?php

/**
 * Implements hook_theme().
 */
function custom_form_theme($existing, $type, $theme, $path)
{
    return array(
        'preview_form' => array(
            'variables' => array(
                'message' => NULL
            ),
        ),
    );
}

/**
 * @param $variables
 */
function template_preprocess_preview_form(&$variables)
{
    if (isset($variables['message']) && !empty($variables['message'])) {
        foreach ($variables['message']['message'] as $key => $value) {
            $variables['message'][$key] = $value;
        }
    }
}

/**
 * @custom css style
 * */

function custom_form_page_attachments(array &$variables)
{
    $variables['#attached']['library'][] = 'custom_form/custom_style';
}